export default [
    {
        OrderID: 1,
        TimeStamp: "2g",
        StatusID: 2,
        Note: "Delicious",
        Total: 250,
        ReceiverPhone: "0901517531",
        ReceiverAddress: "tran mai ninh",
        ReceiverName: "huy dep trai",
    },
    {
        OrderID: 2,
        TimeStamp: "2g",
        StatusID: 2,
        Note: "Delicious",
        Total: 250,
        ReceiverPhone: "0901517531",
        ReceiverAddress: "tran mai ninh",
        ReceiverName: "huy dep trai",
    },
    {
        OrderID: 3,
        TimeStamp: "2g",
        StatusID: 2,
        Note: "Delicious",
        Total: 250,
        ReceiverPhone: "0901517531",
        ReceiverAddress: "tran mai ninh",
        ReceiverName: "huy dep trai",
    },
    {
        OrderID: 3,
        TimeStamp: "2g",
        StatusID: 2,
        Note: "Delicious",
        Total: 250,
        ReceiverPhone: "0901517531",
        ReceiverAddress: "tran mai ninh",
        ReceiverName: "huy dep trai",
    },
    {
        OrderID: 3,
        TimeStamp: "2g",
        StatusID: 2,
        Note: "Delicious",
        Total: 250,
        ReceiverPhone: "0901517531",
        ReceiverAddress: "tran mai ninh",
        ReceiverName: "huy dep trai",
    },
];